# (c) 2024 Silvino R.
# SPDX-License-Identifier: GPL-3.0-or-later

MOUSEKEY_ENABLE = no

VIA_ENABLE = yes
VIAL_ENABLE = yes
RGB_MATRIX_ENABLE = yes
VIALRGB_ENABLE = yes

LTO_ENABLE = yes
# VIAL_INSECURE = yes

CAFFEINE_ENABLE = yes
KONAMI_ENABLE = yes
SOCD_CLEANER_ENABLE = yes

## --- Debug ---
# CONSOLE_ENABLE = yes
# NKRO_ENABLE = no
# EXTRAKEY_ENABLE = no
# OPT_DEFS += -DDEBUG
